version: 0.2

env:
  secrets-manager:
    DOCKERHUB_TOKEN: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/dockerhub-5K8Q1a:DOCKERHUB_TOKEN
    DOCKERHUB_USERNAME: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/dockerhub-5K8Q1a:DOCKERHUB_USERNAME
    DB_DATABASE: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:DB_DATABASE
    DB_HOST: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:DB_HOST
    DB_PASSWORD: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:DB_PASSWORD
    DB_PORT: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:DB_PORT
    DB_USER: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:DB_USER
  IMAGE_NAME: "$DOCKERHUB_USERNAME/simple-api:dev"
phases:
  pre_build:
    commands:
      - echo Setting variables dockerfile...
      - sed -i "s/API_PORT_VALUE/$API_PORT/g" Dockerfile
      - sed -i "s/DB_DATABASE_VALUE/$DB_DATABASE/g" Dockerfile
      - sed -i "s/DB_HOST_VALUE/$DB_HOST/g" Dockerfile
      - sed -i "s/DB_PORT_VALUE/$DB_PORT/g" Dockerfile
      - sed -i "s/DB_USER_VALUE/$DB_USER/g" Dockerfile
      - sed -i "s/DB_PASSWORD_VALUE/$DB_PASSWORD/g" Dockerfile
      - echo Login to Docker Hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
      commands:
        - echo Build and send image to Docker Hub...
        - docker build -t $IMAGE_NAME .
        - docker push $IMAGE_NAME
  post_build:
      commands:
        - echo Finish build...
