version: 0.2

env:
  secrets-manager:
    OWNER: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:OWNER
    AWS_REGION: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:AWS_REGION
    PROJECT_NAME: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:PROJECT_NAME
    API_PORT: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:API_PORT
    DB_DATABASE: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:DB_DATABASE
    DB_HOST: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:DB_HOST
    DB_PASSWORD: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:DB_PASSWORD
    DB_PORT: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:DB_PORT
    DB_USER: arn:aws:secretsmanager:us-east-1:455462641947:secret:/kxc-desafio-tecnico/terraform-secrets-3vtkan:DB_USER
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $OWNER.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Setting variables dockerfile...
      - sed -i "s/API_PORT_VALUE/$API_PORT/g" Dockerfile
      - sed -i "s/DB_DATABASE_VALUE/$DB_DATABASE/g" Dockerfile
      - sed -i "s/DB_HOST_VALUE/$DB_HOST/g" Dockerfile
      - sed -i "s/DB_PORT_VALUE/$DB_PORT/g" Dockerfile
      - sed -i "s/DB_USER_VALUE/$DB_USER/g" Dockerfile
      - sed -i "s/DB_PASSWORD_VALUE/$DB_PASSWORD/g" Dockerfile
  build:
      commands:
        - echo Build image `date`...
        - docker build -t $PROJECT_NAME:DEV .
        - docker tag $PROJECT_NAME:DEV $OWNER.dkr.ecr.$AWS_REGION.amazonaws.com/$PROJECT_NAME:DEV
  post_build:
      commands:
        - echo Pushing the Docker image `date`...
        - docker push $OWNER.dkr.ecr.$AWS_REGION.amazonaws.com/$PROJECT_NAME:DEV
        - echo Finish build `date`...
